### ISSUE TITLE
Outdated faraday due to faraday_hal_middleware

### ISSUE THREAD

**Issue by espen** [codegram/hyperclient#129]
faraday_hal_middleware is [using](https://github.com/fetch/faraday_hal_middleware/blob/master/faraday_hal_middleware.gemspec) an old version of Faraday: ```faraday_middleware', ['>= 0.9', '< 0.10']```.

This blocks hyperclient from using the latest version of faraday (currently 0.13.1).

faraday_hal_middleware hasn't been updated for a while but I have submitted a pull request here: https://github.com/fetch/faraday_hal_middleware/pull/1

**Comment by ivoanjo** [comment]
May I suggest also pinging the author via [twitter](https://twitter.com/koenpunt), for instance? I've had success with that approach in the past.

Otherwise, as `faraday_hal_middleware` is trivial enough, it may be useful to look at either getting `faraday_hal_middleware` into `faraday_middleware` (plan B) or just import it into hyperclient (plan C?) (this change would also be a great chance to change it to use multijson instead of hardcoding the json gem).

**Comment by dblock** [comment]
Good idea(s) @ivoanjo. On JSON note that in Grape we got rid of multi_json and are considering it just one of possible JSON adapters. See https://github.com/ruby-grape/grape/pull/1623

**Comment by ivoanjo** [comment]
Ah, interesting approach. I'm not a huge fan of just picking when the library is required (e.g. if somehow something causes `grape` to be loaded before `multi_json`, json decoding performance will suddendly go down a cliff without a lot of warning), and thus I would suggest an additional mechanism that would allow you to specifically pick multi_json (something like `Hyperclient.json_decoder = :multi_json`; this way if you have this on your app no amount of `require` reordering will change your configuration).

Just my 0.02c but other than that I agree that some may not want the burden of `multi_json` on their app ;)

At @Talkdesk we had our own `faraday_hal_middleware` replacements that used multi_json exactly because we wanted to be able to pick the json back-end (use Oj for MRI Ruby and jrjackson for JRuby), so we ended up passing in `default: false` and doing our own faraday configuration manually.

**Comment by dblock** [comment]
Yes, explicit is better. Grape had to do this because of backwards compatibility.

**Comment by dblock** [comment]
I opened https://github.com/fetch/faraday_hal_middleware/issues/3, lets see if we can get some attention first.

**Comment by dblock** [comment]
@espen Do you want to finish this one now that faraday_hal_middleware 0.1.0 has been released?
